config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :path => '', :path_names => {:sign_in => 'signin_as_admin', :sign_out => 'signout_as_admin'}, controllers: { sessions: 'admin/sessions' }
  devise_for :accounts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "static_pages#dashboard"

 resources :accounts
 resources :workshops
 resources :lessons do
  collection do
   patch :sort
  end
 end

 resources :workshops do
 resources :lessons
end

 namespace :admin do
  root "static_pages#dashboard"
  resources :static_pages
  resources :accounts
  resources :workshops
  resources :lessons
  resources :workshops do
   resources :lessons
  end
 end

end

app/models/workshop.rb
class Workshop < ApplicationRecord
  include ImageUploader::Attachment.new(:image)

  validates :title, presence: true, length: { within: 1..100 }
  validates :discount, numericality: { less_than_or_equal_to: 100 }

  belongs_to :account

  scope :published, -> { where(status: 'published') }
  scope :drafts, -> { where(status: 'draft') }

  has_many :lessons

end

app/controllers/admin/workshops_controller.rb
class Admin::WorkshopsController < ApplicationController
  before_action :authenticate_admin!

  layout "admin"

  def show
    @workshop = Workshop.find(params[:id])
  end

  def index
    @workshops = Workshop.all
  end

  def new
    @workshop = Workshop.new
  end

  def edit
    @workshop = Workshop.find(params[:id])
  end

  def update
    @workshop = Workshop.find(params[:id])
    if @workshop.update_attributes(admin_workshop_params)
      flash[:notice] = 'Changes updated successfully!'
      redirect_back(fallback_location: root_path)
    else
      flash[:notice] = 'Could not update, Please try again'
      render :edit, alert: "Could not update, Please try again"
    end
  end

  def create
    @workshop = Workshop.new(admin_workshop_params)

    respond_to do |format|
      if @workshop.save
        format.html { redirect_to admin_workshops_url, notice: 'Workshop was successfully created.' }
        format.json { render json: @workshop, status: :created, location: [:admin,@workshop] }
      else
        format.html { render action: "new" }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @workshop.destroy
    redirect_to root_url, notice: "Successfully deleted the workshop"
  end

  private

  def set_workshop
    @workshop = current_workshop
  end

  def admin_workshop_params
    params.require(:workshop).permit(:title, :subtitle, :description, :account_id, :difficulty, :category, :language, :requirements, :outcomes, :cost, :discount, :image, :remove_image)
  end

end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_action :set_workshop, only: [:show]

  def index
    @workshops = Workshop.all
  end

  def show
  end

  private
   def set_workshop
     @workshop = Workshop.find(params[:id])
   end
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/admin/workshops/edit.html.erb
<div class="row">
  <%= render partial: 'layouts/admin_sidebar' %>
  <div class="col-12 col-lg-10">
    <div class="card">
      <div class="card-header">
        Edit Workshop
      </div>
      <%= form_for([:admin,@workshop]) do |f| %>
        <div class="card-body">
          <% if @workshop.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@workshop.errors.count, "error") %> prohibited this workshop from being saved:</h2>
              <ul>
              <% @workshop.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class="row">
            <div class="col-md-8">
              <div class="form-group">
                <label>Title</label>
                  <%= f.text_field :title, class: 'form-control', autofocus: true, autocomplete: "title" %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label>Workshop ID</label>
                <input class="form-control" id="disabledInput" type="text" placeholder="<%= @workshop.id %>" disabled>
              </div>
            </div>
            <div class="col-md-8">
              <div class="form-group">
                <label>Subtitle</label>
                <%= f.text_area :subtitle, rows: '2', class: 'form-control', autofocus: true, autocomplete: "subtitle" %>
              </div>
            </div>
            <div class="col-md-8">
              <div class="form-group">
                <label>Description</label>
                <%= f.text_area :description, rows: '5', class: 'form-control', autofocus: true, autocomplete: "subtitle" %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label>Owner ID</label>
                <%= f.number_field :account_id, class: 'form-control', autofocus: true, autocomplete: "account_id" %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label>Cost</label>
                <%= f.number_field :cost, class: 'form-control', autofocus: true, autocomplete: "cost" %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label>Discount (%)</label>
                <%= f.number_field :discount, class: 'form-control', autofocus: true, autocomplete: "discount" %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label>Difficulty Level</label>
                <%= f.text_field :difficulty, class: 'form-control', autofocus: true, autocomplete: "difficulty" %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label>Category</label>
                <%= f.text_field :category, class: 'form-control', autofocus: true, autocomplete: "category" %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label>Language</label>
                <%= f.text_field :language, class: 'form-control', autofocus: true, autocomplete: "language" %>
              </div>
            </div>
            <hr>
            <div class="col-md-4">
              <div class="form-group">
                <label>Status</label>
                <%= f.text_field :status, class: 'form-control', autofocus: true, autocomplete: "status" %>
              </div>
            </div>
            <div class="col-md-8">
              <div class="form-group">
                <label>Image Info</label>
                <% if @workshop.image.present? %>
                <%= image_tag @workshop.image_url(:original), style: "width:100%;" %>
                <% end %>
                <textarea rows="5" class="form-control" value="" disabled><%= @workshop.image_data %></textarea>
              </div>
              <div class="form-group">
                <label>Change Image?</label>
                <%= f.file_field :image, class: 'form-control' %>
              </div>
               <div class="card">
                <div class="card-body">
                 <div class="card-header">
                  <span style="padding-right: 5px;">Workshop Curriculum</span>
                  <%= link_to 'Add Lesson', new_admin_workshop_lesson_path(@workshop), class: "btn btn-primary btn-sm my-10" %>
                 </div>
                 <div id="lessons" class="list-group" data-url="<%= sort_lessons_path %>">
                  <% if @workshop.lessons.count == 0 %>
                   <div class="list-group-item">No lessons for this workshop found. Please create one!</div>
                  <% else %>
                   <% @workshop.lessons.order(order: :asc).each_with_index do |lesson| %>
                    <%= link_to lesson.title, edit_admin_workshop_lesson_path(@workshop, lesson), class: "list-group-item", id: dom_id(lesson) %>
                   <% end %>
                  <% end %>
                 </div>
                </div>
               </div>
            </div>
          </div>
          <hr>
          <span>
            <%= link_to 'Back', admin_workshops_path, :class => 'btn btn-secondary' %>
          </span>
          <span>
            <%= f.submit 'Save Workshop', :class => 'btn btn-primary' %>
          </span>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
$(function() {
 $('#lessons').sortable({
  update: function( event, ui ) {
   $.ajax({
    type: 'PATCH',
    url: $(this).data("url"),
    dataType: 'json',
    data: $(this).sortable('serialize'),
   });
  }
 });
});
</script>

app/views/admin/workshops/index.html.erb
<div class="row">
  <%= render partial: 'layouts/admin_sidebar' %>
  <div class="col-12 col-lg-10">
    <div class="card">
      <div class="card-header">Manage Workshops</div>
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>Workshop ID</th>
            <th>Title</th>
            <th>Created At</th>
            <th><i class="fa fa-pencil" aria-hidden="true"></i></th>
            <th><i class="fa fa-trash" aria-hidden="true"></i></th>
          </tr>
        </thead>
        <tbody>
          <% @workshops.each_with_index do |workshop, i| %>
            <tr>
              <th scope="row"><%= i+1 %></th>
              <td><%= workshop.id %></td>
              <td><%= workshop.title %></td>
              <td><%= time_ago_in_words(workshop.created_at.localtime) %> ago</td>
              <td>
                <%= link_to edit_admin_workshop_path(workshop) do %>
                  <i class="fa fa-pencil" aria-hidden="true"></i>
                <% end %>
              </td>
              <td>
                <%= link_to admin_workshop_path(workshop), method: :delete, data: { confirm: "You sure?" } do %>
                  <i class="fa fa-trash" aria-hidden="true"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/workshops/new.html.erb
<div class="row">
  <%= render partial: 'layouts/admin_sidebar' %>
  <div class="col-12 col-lg-10">
    <div class="card">
      <div class="card-header">
        Add New Workshop
      </div>
      <%= form_for([:admin,@workshop]) do |f| %>
        <div class="card-body">
          <% if @workshop.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@workshop.errors.count, "error") %> prohibited this workshop from being saved:</h2>
              <ul>
              <% @workshop.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class="row">
            <div class="col-md-8">
              <div class="form-group">
                <label>Title</label>
                  <%= f.text_field :title, class: 'form-control', autofocus: true, autocomplete: "title" %>
              </div>
            </div>
            <div class="col-md-8">
              <div class="form-group">
                <label>Subtitle</label>
                <%= f.text_area :subtitle, rows: '2', class: 'form-control', autofocus: true, autocomplete: "subtitle" %>
              </div>
            </div>
            <div class="col-md-8">
              <div class="form-group">
                <label>Description</label>
                <%= f.text_area :description, rows: '5', class: 'form-control', autofocus: true, autocomplete: "subtitle" %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label>Owner ID</label>
                <%= f.number_field :account_id, class: 'form-control', autofocus: true, autocomplete: "account_id" %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label>Cost</label>
                <%= f.number_field :cost, class: 'form-control', autofocus: true, autocomplete: "cost" %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label>Discount (%)</label>
                <%= f.number_field :discount, class: 'form-control', autofocus: true, autocomplete: "discount" %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label>Difficulty Level</label>
                <%= f.text_field :difficulty, class: 'form-control', autofocus: true, autocomplete: "difficulty" %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label>Category</label>
                <%= f.text_field :category, class: 'form-control', autofocus: true, autocomplete: "category" %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label>Language</label>
                <%= f.text_field :language, class: 'form-control', autofocus: true, autocomplete: "language" %>
              </div>
            </div>
              <hr>
            <div class="col-md-12">
              <div class="form-group">
                <%= f.label :image %>
                <%= f.file_field :image, class: 'form-control' %>
              </div>
            </div>
          </div>
          <hr>
          <span>
            <%= link_to 'Back', admin_workshops_path, :class => 'btn btn-secondary' %>
          </span>
          <span>
            <%= f.submit 'Create Workshop', :class => 'btn btn-primary' %>
          </span>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>