config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :path => '', :path_names => {:sign_in => 'signin_as_admin', :sign_out => 'signout_as_admin'}, controllers: { sessions: 'admin/sessions' }
  devise_for :accounts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "static_pages#dashboard"

 resources :accounts
 resources :workshops
 resources :lessons do
  collection do
   patch :sort
  end
 end

 resources :workshops do
 resources :lessons
end

 namespace :admin do
  root "static_pages#dashboard"
  resources :static_pages
  resources :accounts
  resources :workshops
  resources :lessons
  resources :workshops do
   resources :lessons
  end
 end

end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable

  include ImageUploader.attachment(:image)

  protected
  def confirmation_required?
	false
  end
end

app/controllers/admin/accounts_controller.rb
class Admin::AccountsController < ApplicationController
  before_action :authenticate_admin!

  layout "admin"
  
  def show
    @account = Account.find(params[:id])
  end

  def index
    @accounts = Account.all
  end

  def new
    @account = Account.new
  end

  def edit
    @account = Account.find(params[:id])
  end

  def update
    @account = Account.find(params[:id])
    if @account.update_attributes(admin_account_params)
      flash[:notice] = 'Changes updated successfully!'
      redirect_back(fallback_location: root_path)
    else
      flash[:notice] = 'Could not update, Please try again'
      render :edit, alert: "Could not update, Please try again"
    end
  end

  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to admin_accounts_url, notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: [:admin,@account] }
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @account.destroy
    redirect_to root_url, notice: "Successfully deleted the account"
  end

  private

  def set_account
    @account = current_account
  end

  def admin_account_params
    params.require(:account).permit(:first_name, :last_name, :email, :unconfirmed_email, :image, :remove_image)
  end

end

app/views/admin/accounts/edit.html.erb
<div class="row">
  <%= render partial: 'layouts/admin_sidebar' %>
  <div class="col-12 col-lg-10">
    <div class="card">
      <div class="card-header">
        Edit User
      </div>
      <%= form_for([:admin,@account]) do |f| %>
        <div class="card-body">
          <div class="row">
            <div class="col-md-4">
              <div class="form-group">
                <label>User ID</label>
                 <%= f.text_field :id, :id => "id", :class => "form-control" %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label>Full Name</label>
                <input type="text" class="form-control" value="<%= @account.first_name %> <%= @account.last_name %>" disabled>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label>First Name</label>
                   <%= f.text_field :first_name, :id => "first_name", :class => "form-control" %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label>Last Name</label>
                <%= f.text_field :last_name, :id => "last_name", :class => "form-control" %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label>E-mail</label>
                <%= f.text_field :email, :id => "email", :class => "form-control" %>
              </div>
            </div>
            <div class="col-md-12">
              <hr>
              <div class="form-group">
                <label>Image Info</label>
                <textarea rows="5" class="form-control" value="" disabled><%= @account.image_data %></textarea>
              </div>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-md-4">
              <div class="form-group">
                <label>Created At</label>
                  <input type="text" class="form-control" value="<%= @account.created_at %>" disabled>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label>Updated At</label>
                  <input type="text" class="form-control" value="<%= @account.updated_at %>" disabled>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
              <label>Unconfirmed Email</label>
                <%= f.text_field :unconfirmed_email, :id => "unconfirmed_email", :class => "form-control" %>
              </div>
            </div>
            <div class="col-md-4">
              <hr>
              <div class="form-group">
                <label>Confirmed At</label>
                  <input type="text" class="form-control" value="<%= @account.confirmed_at %>" disabled>
              </div>
            </div>
            <div class="col-md-4">
              <hr>
              <div class="form-group">
                <label>Confirmation Email Sent At</label>
                  <input type="text" class="form-control" value="<%= @account.confirmation_sent_at %>" disabled>
              </div>
            </div>
            <div class="col-md-4">
              <hr>
              <div class="form-group">
                <label>Confirmation Token</label>
                  <input type="text" class="form-control" value="<%= @account.confirmation_token %>" disabled>
              </div>
            </div>
            <div class="col-md-8">
              <div class="form-group">
                <label>Image Info</label>
                <% if @account.image.present? %>
                <%= image_tag @account.image_url(:original), style: "width:10%;" %>
                <% end %>
                <textarea rows="5" class="form-control" value="" disabled><%= @account.image_data %></textarea>
              </div>
              <div class="form-group">
                <label>Change Image?</label>
                <%= f.file_field :image, class: 'form-control' %>
              </div>
            </div>
          </div>
          <span>
            <%= link_to 'Back', admin_accounts_path, :class => 'btn btn-secondary' %>
          </span>
          <span>
            <%= f.submit 'Update', :class => 'btn btn-primary' %>
          </span>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/accounts/index.html.erb
<div class="row">
  <%= render partial: 'layouts/admin_sidebar' %>
  <div class="col-12 col-lg-10">
    <div class="card">
      <div class="card-header">Manage Users</div>
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>User ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Confirmed?</th>
            <th><i class="fa fa-pencil" aria-hidden="true"></i></th>
            <th><i class="fa fa-trash" aria-hidden="true"></i></th>
          </tr>
        </thead>
        <tbody>
          <% @accounts.each_with_index do |account, i| %>
            <tr>
              <th scope="row"><%= i+1 %></th>
              <td><%= account.id %></td>
              <td><%= account.first_name %></td>
              <td><%= account.last_name %></td>
              <td><%= account.email %></td>
              <td><% if account.confirmed_at.present? %><%= time_ago_in_words(account.confirmed_at.localtime) %> ago<% else %>Not yet<% end %></td>
              <td>
                <%= link_to edit_admin_account_path(account) do %>
                  <i class="fa fa-pencil" aria-hidden="true"></i>
                <% end %>
              </td>
              <td>
                <%= link_to admin_account_path(account), method: :delete, data: { confirm: "You sure?" } do %>
                  <i class="fa fa-trash" aria-hidden="true"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/accounts/new.html.erb
<div class="row">
 <%= render partial: 'layouts/admin_sidebar' %>
 <div class="col-12 col-lg-10">
  <div class="card">
   <div class="card-header">
    Add New User
   </div>
   <%= form_for([:admin,@account]) do |f| %>
    <div class="card-body">
     <% if @account.errors.any? %>
      <div id="error_explanation">
       <h2><%= pluralize(@account.errors.count, "error") %> prohibited this user from being saved:</h2>
       <ul>
       <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
       <% end %>
       </ul>
      </div>
     <% end %>
     <div class="row">
      <div class="col-md-4">
       <div class="form-group">
        <label>First Name</label>
         <%= f.text_field :first_name, class: 'form-control', autofocus: true, autocomplete: "first_name" %>
       </div>
      </div>
      <div class="col-md-4">
       <div class="form-group">
        <label>Last Name</label>
        <%= f.text_field :last_name, class: 'form-control', autofocus: true, autocomplete: "last_name" %>
       </div>
      </div>
      <div class="col-md-4">
       <div class="form-group">
        <label>E-mail</label>
        <%= f.email_field :email, class: 'form-control', autofocus: true, autocomplete: "email" %>
       </div>
      </div>
      <div class="col-md-4">
       <div class="form-group">
        <label>Password</label>
        <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br />
        <%= f.password_field :password, class: 'form-control', autocomplete: "off" %>
       </div>
      </div>
      <div class="col-md-4">
       <div class="form-group">
        <label>Password Confirmation</label>
         <%= f.password_field :password_confirmation, class: 'form-control', autocomplete: "off" %>
       </div>
      </div>
      <div class="col-md-4">
       <div class="form-group">
       </div>
      </div>
       <hr>
      <div class="col-md-12">
       <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image, class: 'form-control' %>
       </div>
      </div>
     </div>
     <hr>
     <span>
      <%= link_to 'Back', admin_accounts_path, :class => 'btn btn-secondary' %>
     </span>
     <span>
      <%= f.submit 'Create User', :class => 'btn btn-primary' %>
     </span>
    </div>
   </div>
   <% end %>
  </div>
 </div>
</div>