config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :path => '', :path_names => {:sign_in => 'signin_as_admin', :sign_out => 'signout_as_admin'}, controllers: { sessions: 'admin/sessions' }
  devise_for :accounts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "static_pages#dashboard"

 resources :accounts
 resources :workshops
 resources :lessons do
  collection do
   patch :sort
  end
 end

 resources :workshops do
 resources :lessons
end

 namespace :admin do
  root "static_pages#dashboard"
  resources :static_pages
  resources :accounts
  resources :workshops
  resources :lessons
  resources :workshops do
   resources :lessons
  end
 end

end

app/models/lesson.rb
class Lesson < ApplicationRecord

  validates :title, presence: true, length: { within: 5..50 }
  validates :workshop_id, presence: true
  validates :account_id, presence: true
  belongs_to :workshop

end

app/controllers/admin/lessons_controller.rb
class Admin::LessonsController < ApplicationController
 before_action :authenticate_admin!

 layout "admin"

 def show
  @lesson = Lesson.find(params[:id])
 end

 def index
  @lessons = Lesson.all
 end

 def new
  @workshop = Workshop.find(params[:workshop_id])
  @lesson = Lesson.new
 end

 def edit
  @workshop = Workshop.find(params[:workshop_id])
  @lesson = Lesson.find(params[:id])
 end

 def update
  @lesson = Lesson.find(params[:id])
  if @lesson.update_attributes(admin_lesson_params)
   flash[:notice] = 'Changes updated successfully!'
   redirect_back(fallback_location: root_path)
  else
   flash[:notice] = 'Could not update, Please try again'
   render :edit, alert: "Could not update, Please try again"
  end
 end

 def create
  @workshop = Workshop.find(params[:workshop_id])
  @lesson = Lesson.new(admin_lesson_params)

  respond_to do |format|
   if @lesson.save
    format.html { redirect_to edit_admin_workshop_url(@workshop), notice: 'Lesson was successfully created.' }
    format.json { render json: @lesson, status: :created, location: [:admin,@lesson] }
   else
    format.html { render action: "new" }
    format.json { render json: @lesson.errors, status: :unprocessable_entity }
   end
  end
 end

 def destroy
  @workshop = Workshop.find(params[:workshop_id])
  @lesson = Lesson.find(params[:id])
  @lesson.destroy
  redirect_to edit_admin_workshop_url(@workshop), notice: "Successfully deleted the lesson"
 end

 private

 def set_lesson
  @lesson = current_lesson
 end

 def admin_lesson_params
  params.require(:lesson).permit(:title, :description, :account_id, :workshop_id, :slug, :video, :order, :video, :remove_video)
 end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
 before_action :authenticate_admin!, only: [:sort]
 before_action :authenticate_account!, only: [:show]

 def show
  @lesson = Lesson.find(params[:id])
 end

 def sort
  params[:lesson].each_with_index do |id, index|
   Lesson.where(id: id).update_all(order: index + 1)
  end
  head :ok
 end

 private

 def set_lesson
  @lesson = current_lesson
 end

 def lesson_params
  params.require(:lesson).permit(:title, :description, :account_id, :workshop_id, :slug, :video, :order, :video, :remove_video)
 end

end

app/views/admin/lessons/edit.html.erb
<div class="row">
  <%= render partial: 'layouts/admin_sidebar' %>
  <div class="col-12 col-lg-10">
    <div class="card">
      <div class="card-header">
        Edit Lesson
        <%= link_to admin_workshop_lesson_path(@workshop, @lesson), method: :delete do %>
            <i class="fa fa-trash-o" aria-hidden="true"></i>
        <% end %>
      </div>
      <%= form_for([:admin,@workshop, @lesson]) do |f| %>
        <div class="card-body">
          <% if @lesson.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>
              <ul>
              <% @lesson.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class="row">
            <div class="col-md-8">
              <div class="form-group">
                <label>Title</label>
                  <%= f.text_field :title, class: 'form-control', autofocus: true, autocomplete: "title" %>
              </div>
            </div>
            <div class="col-md-8">
              <div class="form-group">
                <label>Description</label>
                <%= f.text_area :description, rows: '5', class: 'form-control', autofocus: true, autocomplete: "subtitle" %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label>Owner ID</label>
                <input class="form-control" id="disabledInput" type="text" placeholder="<%= @workshop.account_id %>" disabled>
              </div>
            </div>
              <hr>
            <div class="col-md-12">
              <div class="form-group">

                <br>
                <div>Change video?</div>
                <%= f.file_field :video, class: 'form-control' %>
              </div>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-md-4">
              <div class="form-group">
                <label>Workshop ID</label>
                <input class="form-control" id="disabledInput" type="text" placeholder="<%= @workshop.id %>" disabled>
              </div>
            </div>
            <div class="col-md-8">
              <div class="form-group">
                <label>Workshop Title</label>
                <input class="form-control" id="disabledInput" type="text" placeholder="<%= @workshop.title %>" disabled>
              </div>
            </div>
          </div>
          <hr>
          <span>
            <%= link_to 'Back to Workshop', edit_admin_workshop_path(@workshop), :class => 'btn btn-secondary' %>
          </span>
          <span>
            <%= f.submit 'Save Lesson', :class => 'btn btn-primary' %>
          </span>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/lessons/index.html.erb
<div class="row">
  <%= render partial: 'layouts/admin_sidebar' %>
  <div class="col-12 col-lg-10">
    <div class="card">
      <div class="card-header">Manage Lessons</div>
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>Lesson ID</th>
            <th>Title</th>
            <th>Created At</th>
            <th><i class="fa fa-pencil" aria-hidden="true"></i></th>
            <th><i class="fa fa-trash" aria-hidden="true"></i></th>
          </tr>
        </thead>
        <tbody>
          <% @lessons.each_with_index do |lesson, i| %>
            <tr>
              <th scope="row"><%= i+1 %></th>
              <td><%= lesson.id %></td>
              <td><%= lesson.title %></td>
              <td><%= time_ago_in_words(lesson.created_at.localtime) %> ago</td>
              <td>
                <%= link_to edit_admin_workshop_lesson_path(lesson.workshop_id, lesson) do %>
                  <i class="fa fa-pencil" aria-hidden="true"></i>
                <% end %>
              </td>
              <td>
                <%= link_to admin_workshop_lesson_path(lesson.workshop_id, lesson), method: :delete, data: { confirm: "You sure?" } do %>
                  <i class="fa fa-trash" aria-hidden="true"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/lessons/new.html.erb
<div class="row">
  <%= render partial: 'layouts/admin_sidebar' %>
  <div class="col-12 col-lg-10">
    <div class="card">
      <div class="card-header">
        Add New Lesson
      </div>
      <%= form_for([:admin,@workshop, @lesson]) do |f| %>
        <div class="card-body">
          <% if @lesson.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>
              <ul>
              <% @lesson.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class="row">
            <div class="col-md-8">
              <div class="form-group">
                <label>Title</label>
                  <%= f.text_field :title, class: 'form-control', autofocus: true, autocomplete: "title" %>
              </div>
            </div>
            <div class="col-md-8">
              <div class="form-group">
                <label>Description</label>
                <%= f.text_area :description, rows: '5', class: 'form-control', autofocus: true, autocomplete: "subtitle" %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label>Owner ID</label>
                <input class="form-control" id="disabledInput" type="text" placeholder="<%= @workshop.account_id %>" disabled>
                <%= f.hidden_field :account_id, value: @workshop.account_id %>
              </div>
            </div>
              <hr>
            <div class="col-md-12">
              <div class="form-group">
                <%= f.label :video %>
                <%= f.file_field :video, class: 'form-control' %>
              </div>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-md-4">
              <div class="form-group">
                <label>Workshop ID</label>
                <input class="form-control" id="disabledInput" type="text" placeholder="<%= @workshop.id %>" disabled>
                <%= f.hidden_field :workshop_id, value: @workshop.id %>
              </div>
            </div>
            <div class="col-md-8">
              <div class="form-group">
                <label>Workshop Title</label>
                <input class="form-control" id="disabledInput" type="text" placeholder="<%= @workshop.title %>" disabled>
              </div>
            </div>
          </div>
          <hr>
          <span>
            <%= link_to 'Back to Workshop', edit_admin_workshop_path(@workshop), :class => 'btn btn-secondary' %>
          </span>
          <span>
            <%= f.submit 'Create Lesson', :class => 'btn btn-primary' %>
          </span>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>