config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :path => '', :path_names => {:sign_in => 'signin_as_admin', :sign_out => 'signout_as_admin'}, controllers: { sessions: 'admin/sessions' }
  devise_for :accounts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "static_pages#dashboard"

 resources :accounts
 resources :workshops
 resources :lessons do
  collection do
   patch :sort
  end
 end

 resources :workshops do
 resources :lessons
end

 namespace :admin do
  root "static_pages#dashboard"
  resources :static_pages
  resources :accounts
  resources :workshops
  resources :lessons
  resources :workshops do
   resources :lessons
  end
 end

end

app/views/layouts/_admin_header.html.erb
<!-- Fixed admin navbar (Start) -->
<div class="d-flex sticky-top flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
 <%= image_tag('', height: 35, class: 'my-0 mr-md-auto', alt: "Academy") %>
 <% if admin_signed_in? %>
 <nav class="">
  <a class="p-2 text-dark" href="#">Sidekiq</a>
  <a class="p-2 text-dark" href="#">Users</a>
  <a class="p-2 text-dark" href="#">Workshops</a>
 </nav>
 <% end %>
 <nav class="my-2 my-md-0 mr-md-3">
  <% if admin_signed_in? %>
   <div class="dropdown">
    <a class="btn btn-white dropdown-toggle" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
     Welcome Admin
    </a>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
     <%= link_to destroy_admin_session_url, :method => :delete, class: "dropdown-item" do %>Sign out<% end %>
    </div>
   </div>
  <% else %>
   <%= link_to 'Log In', admin_session_path, class: 'btn btn-outline-primary' %>
  <% end %>
 </nav>
</div>
<!-- Fixed admin navbar (End) -->

app/views/layouts/_admin_sidebar.html.erb
<div class="col-12 col-lg-2">
 <div class="sidebar">
  <div class="card-body">
   <h5><i class="glyphicon glyphicon-file"></i>
    <small><b>WORKSHOPS</b></small>
   </h5>
   <ul class="nav nav-pills">
    <li class="nav-link"><%= link_to 'Manage Workshops', admin_workshops_path %></li>
    <li class="nav-link"><%= link_to 'Add Workshop', new_admin_workshop_path %></li>
   </ul>
   <br>
   <h5><i class="glyphicon glyphicon-user"></i>
    <small><b>USERS</b></small>
   </h5>
   <ul class="nav nav-pills nav-justified">
    <li class="nav-link"><%= link_to 'Manage Users', admin_accounts_path %></li>&nbsp;&nbsp;
    <li class="nav-link"><%= link_to 'New User', new_admin_account_path %></li>
   </ul>
  </div>
 </div>
</div>

app/views/layouts/_alert_messages.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('info', 'info').gsub('warning', 'warning').gsub('notice', 'success')   %>
      toastr['<%= type %>']('<%= f[1] %>', '', {"closeButton": false, "debug": false, "positionClass": "toast-top-full-width", "onclick": null, "showDuration": "300", "hideDuration": "1000", "timeOut": "5000", "extendedTimeOut": "1000", "showEasing": "swing", "hideEasing": "linear", "showMethod": "fadeIn", "hideMethod": "fadeOut" });
    <% end %>
  </script>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="pt-4 my-md-5 pt-md-5 border-top text-center">
 <div class="row">
  <div class="col-6 col-md">
   <h5>Company</h5>
   <ul class="list-unstyled text-small">
    <li><a class="text-muted" href="#">About</a></li>
    <li><a class="text-muted" href="#">Newsroom</a></li>
    <li><a class="text-muted" href="#">Careers</a></li>
   </ul>
  </div>
  <div class="col-6 col-md">
   <h5>Learn</h5>
   <ul class="list-unstyled text-small">
    <li><a class="text-muted" href="#">Workshops</a></li>
    <li><a class="text-muted" href="#">Plans</a></li>
   </ul>
  </div>
  <div class="col-6 col-md">
   <h5>Teach</h5>
   <ul class="list-unstyled text-small">
    <li><a class="text-muted" href="#">How To</a></li>
    <li><a class="text-muted" href="#">Examples</a></li>
   </ul>
  </div>
  <div class="col-6 col-md">
   <h5>Community</h5>
   <ul class="list-unstyled text-small">
    <li><a class="text-muted" href="#">Blog</a></li>
    <li><a class="text-muted" href="#">Help Desk</a></li>
   </ul>
  </div>
 </div>
 <div class="container">
  <span class="text-muted">Academy 2020</span>
 </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Fixed navbar (Start) -->
<div class="d-flex sticky-top flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
  <%= image_tag('', height: 35, class: 'my-0 mr-md-auto', alt: "Academy") %>
  <nav class="my-2 my-md-0 mr-md-3">
    <a class="p-2 text-dark" href="#">Academy for Business</a>
    <a class="p-2 text-dark" href="#">Become an Instructor</a>
  </nav>
  <nav class="my-2 my-md-0 mr-md-3">
	  <% if account_signed_in? %>
	   <div class="dropdown">
	    <a class="btn btn-white dropdown-toggle" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	     <%= current_account.first_name %>
	    </a>
	    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
	     <%= link_to "Settings", edit_account_registration_path, class: 'dropdown-item' %>
	     <div class="dropdown-divider"></div>
	     <%= link_to destroy_account_session_url, :method => :delete, class: "dropdown-item" do %>Sign out<% end %>
	    </div>
	   </div>
	  <% else %>
	   <%= link_to 'Log In', new_account_session_path, class: 'btn btn-outline-primary' %>
	   <%= link_to 'Sign Up', new_account_registration_path, class: 'btn btn-primary' %>
	  <% end %>
  </nav>
</div>
<!-- Fixed navbar (End) -->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
 <head>
  <title>Academy</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag '//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/le-frog/jquery-ui.min.css' %>
  <script src="/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
 </head>

 <body>
  <%= render 'layouts/admin_header' %>
  <%= render 'layouts/alert_messages' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
 </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Academy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag '//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/le-frog/jquery-ui.min.css' %>
    <script src="/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <%= render partial: "layouts/alert_messages" %>  

    <%= yield %>

    <%= render partial: "layouts/footer" %>
  </body>
</html>